from roles.models import (
    ADMIN_CODE,
    COMMANDER_CODE,
    DISPATCHER_CODE,
    OPERATOR_CODE,
    TECHNICIAN_CODE,
    VIEWER_CODE,
)

# Users
PERMISSION_USERS_MANAGE_ROLES = "users.manage_roles"
PERMISSION_USERS_CREATE = "users.create"
PERMISSION_USERS_ACTIVATE_DEACTIVATE = "users.activate_deactivate"

# Drones
PERMISSION_DRONES_CREATE = "drones.create"
PERMISSION_DRONES_UPDATE = "drones.update"
PERMISSION_DRONES_DECOMMISSION = "drones.decommission"
PERMISSION_DRONES_VIEW = "drones.view"
PERMISSION_DRONES_IMPORT_EXPORT = "drones.import_export"

# Missions
PERMISSION_MISSIONS_VIEW = "missions.view"
PERMISSION_MISSIONS_CREATE = "missions.create"
PERMISSION_MISSIONS_ASSIGN = "missions.assign"
PERMISSION_MISSIONS_UPDATE_STATUS = "missions.update_status"

# Maintenance
PERMISSION_MAINTENANCE_VIEW = "maintenance.view"
PERMISSION_MAINTENANCE_MANAGE = "maintenance.manage"

# Specifications
PERMISSION_SPECIFICATIONS_VIEW = "specifications.view"
PERMISSION_SPECIFICATIONS_MANAGE = "specifications.manage"

# Write-off
PERMISSION_WRITEOFF_VIEW = "writeoff.view"
PERMISSION_WRITEOFF_CREATE = "writeoff.create"
PERMISSION_WRITEOFF_AUTHORIZE = "writeoff.authorize"

# Media
PERMISSION_MEDIA_UPLOAD = "media.upload"
PERMISSION_MEDIA_VIEW = "media.view"

# Audit logs
PERMISSION_AUDIT_LOGS_VIEW_ALL = "audit_logs.view_all"
PERMISSION_AUDIT_LOGS_VIEW_OWN = "audit_logs.view_own"

# Profile
PERMISSION_PROFILE_VIEW_OWN = "profile.view_own"
PERMISSION_PROFILE_UPDATE_OWN = "profile.update_own"
PERMISSION_PROFILE_RESET_PASSWORD_OWN = "profile.reset_password_own"

ROLE_PERMISSION_MATRIX = {
    ADMIN_CODE: {
        PERMISSION_USERS_MANAGE_ROLES,
        PERMISSION_USERS_CREATE,
        PERMISSION_USERS_ACTIVATE_DEACTIVATE,
        PERMISSION_DRONES_CREATE,
        PERMISSION_DRONES_UPDATE,
        PERMISSION_DRONES_DECOMMISSION,
        PERMISSION_DRONES_VIEW,
        PERMISSION_DRONES_IMPORT_EXPORT,
        PERMISSION_MISSIONS_VIEW,
        PERMISSION_MISSIONS_CREATE,
        PERMISSION_MISSIONS_ASSIGN,
        PERMISSION_MISSIONS_UPDATE_STATUS,
        PERMISSION_MEDIA_UPLOAD,
        PERMISSION_MEDIA_VIEW,
        PERMISSION_MAINTENANCE_VIEW,
        PERMISSION_MAINTENANCE_MANAGE,
        PERMISSION_SPECIFICATIONS_VIEW,
        PERMISSION_SPECIFICATIONS_MANAGE,
        PERMISSION_WRITEOFF_VIEW,
        PERMISSION_WRITEOFF_CREATE,
        PERMISSION_WRITEOFF_AUTHORIZE,
        PERMISSION_AUDIT_LOGS_VIEW_ALL,
        PERMISSION_PROFILE_VIEW_OWN,
        PERMISSION_PROFILE_UPDATE_OWN,
        PERMISSION_PROFILE_RESET_PASSWORD_OWN,
    },
    COMMANDER_CODE: {
        PERMISSION_DRONES_VIEW,
        PERMISSION_SPECIFICATIONS_VIEW,
        PERMISSION_MISSIONS_VIEW,
        PERMISSION_MISSIONS_ASSIGN,
        PERMISSION_MISSIONS_UPDATE_STATUS,
        PERMISSION_MEDIA_VIEW,
        PERMISSION_MAINTENANCE_VIEW,
        PERMISSION_WRITEOFF_VIEW,
        PERMISSION_WRITEOFF_AUTHORIZE,
        PERMISSION_AUDIT_LOGS_VIEW_OWN,
        PERMISSION_PROFILE_VIEW_OWN,
        PERMISSION_PROFILE_UPDATE_OWN,
        PERMISSION_PROFILE_RESET_PASSWORD_OWN,
    },
    DISPATCHER_CODE: {
        PERMISSION_DRONES_VIEW,
        PERMISSION_SPECIFICATIONS_VIEW,
        PERMISSION_MISSIONS_VIEW,
        PERMISSION_MISSIONS_CREATE,
        PERMISSION_MISSIONS_ASSIGN,
        PERMISSION_MEDIA_VIEW,
        PERMISSION_AUDIT_LOGS_VIEW_OWN,
        PERMISSION_PROFILE_VIEW_OWN,
        PERMISSION_PROFILE_UPDATE_OWN,
        PERMISSION_PROFILE_RESET_PASSWORD_OWN,
    },
    OPERATOR_CODE: {
        PERMISSION_DRONES_VIEW,
        PERMISSION_SPECIFICATIONS_VIEW,
        PERMISSION_MISSIONS_VIEW,
        PERMISSION_MISSIONS_UPDATE_STATUS,
        PERMISSION_MEDIA_UPLOAD,
        PERMISSION_MEDIA_VIEW,
        PERMISSION_AUDIT_LOGS_VIEW_OWN,
        PERMISSION_PROFILE_VIEW_OWN,
        PERMISSION_PROFILE_UPDATE_OWN,
        PERMISSION_PROFILE_RESET_PASSWORD_OWN,
    },
    TECHNICIAN_CODE: {
        PERMISSION_DRONES_VIEW,
        PERMISSION_SPECIFICATIONS_VIEW,
        PERMISSION_SPECIFICATIONS_MANAGE,
        PERMISSION_MAINTENANCE_VIEW,
        PERMISSION_MAINTENANCE_MANAGE,
        PERMISSION_WRITEOFF_VIEW,
        PERMISSION_WRITEOFF_CREATE,
        PERMISSION_AUDIT_LOGS_VIEW_OWN,
        PERMISSION_PROFILE_VIEW_OWN,
        PERMISSION_PROFILE_UPDATE_OWN,
        PERMISSION_PROFILE_RESET_PASSWORD_OWN,
    },
    VIEWER_CODE: {
        PERMISSION_DRONES_VIEW,
        PERMISSION_SPECIFICATIONS_VIEW,
        PERMISSION_MISSIONS_VIEW,
        PERMISSION_MAINTENANCE_VIEW,
        PERMISSION_WRITEOFF_VIEW,
        PERMISSION_MEDIA_VIEW,
        PERMISSION_AUDIT_LOGS_VIEW_OWN,
        PERMISSION_PROFILE_VIEW_OWN,
        PERMISSION_PROFILE_UPDATE_OWN,
        PERMISSION_PROFILE_RESET_PASSWORD_OWN,
    },
}
