from drones.models import Drone


DRONE_MODEL_CLASSIFICATIONS = {
    "Shark Recon 7": [Drone.CLASSIFICATION_RECONNAISSANCE, Drone.CLASSIFICATION_SURVEILLANCE],
    "Viper Strike 5": [Drone.CLASSIFICATION_COMBAT],
    "Banshee Cargo 6": [Drone.CLASSIFICATION_TRANSPORT, Drone.CLASSIFICATION_COMBAT],
    "Atlas Relay 8": [Drone.CLASSIFICATION_TRANSPORT, Drone.CLASSIFICATION_SURVEILLANCE],
    "Kestrel Mini 4": [Drone.CLASSIFICATION_RECONNAISSANCE],
    "Guardian Hex 6": [Drone.CLASSIFICATION_SURVEILLANCE],
    "Raven Attack 5": [Drone.CLASSIFICATION_COMBAT],
}
