# Generated by Django 6.0.4 on 2026-05-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userroleauditlog"),
        ("accounts", "0002_userstatuslog"),
    ]

    operations = []
