# Generated by Django 6.0.4 on 2026-05-16 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userroleauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                            ("USER_CREATED", "User Created"),
                            ("ROLE_CHANGED", "Role Changed"),
                            ("ACCOUNT_ACTIVATED", "Account Activated"),
                            ("ACCOUNT_DEACTIVATED", "Account Deactivated"),
                            ("PROFILE_UPDATED", "Profile Updated"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("PASSWORD_RESET_REQUESTED", "Password Reset Requested"),
                            ("PERMISSION_DENIED", "Permission Denied"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User performing the action (can be Null for system actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User on whom the action was taken",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ("-created_at",),
            },
        ),
    ]
