# Generated by Django 6.0.4 on 2026-05-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auditlog"),
        ("accounts", "0003_merge_0002_userroleauditlog_0002_userstatuslog"),
    ]

    operations = []
