# Generated by Django 6.0.4 on 2026-05-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_merge_20260526_1517"),
        ("accounts", "0004_merge_20260528_1108"),
    ]

    operations = []
