# Generated by Django 6.0.5 on 2026-07-03 06:39

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                validators=[
                    accounts.validators.validate_image_size,
                    accounts.validators.validate_image_extension,
                ],
            ),
        ),
    ]
