# Generated by Django 5.2.14 on 2026-06-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userprofile_profile_picture"),
        ("accounts", "0007_user_must_change_password"),
    ]

    operations = []
