# Generated by Django 5.2.14 on 2026-07-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_merge_20260629_2257"),
        ("accounts", "0008_usersession"),
    ]

    operations = []
