# Generated by Django 5.2.14 on 2026-07-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_merge_0008_merge_20260629_2257_0008_usersession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="session_key",
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name="usersession",
            constraint=models.UniqueConstraint(
                fields=("user", "session_key"), name="unique_user_session"
            ),
        ),
    ]
