"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from decouple import config
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env variables ]
dotenv_path = BASE_DIR / ".env"
load_dotenv(dotenv_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("Django secret key is required!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "drones",
    "roles",
    "missions",
    "media",
    "repairs",
    "rest_framework",
    "django_filters",
    "common",
    "drf_spectacular",
    "storages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
        "CONN_MAX_AGE": int(config("DB_CONN_MAX_AGE", default="600")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "accounts.User"

default_authentication_classes = [
    "rest_framework.authentication.SessionAuthentication",
]

if DEBUG:
    default_authentication_classes.append(
        "rest_framework.authentication.BasicAuthentication"
    )

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": default_authentication_classes,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "account_activation": os.getenv("THROTTLE_ACCOUNT_ACTIVATION", "5/hour"),
        "password_reset_request": os.getenv(
            "THROTTLE_PASSWORD_RESET_REQUEST",
            "5/hour",
        ),
        "password_reset_confirm": os.getenv(
            "THROTTLE_PASSWORD_RESET_CONFIRM",
            "5/hour",
        ),
        "audit_export": os.getenv("THROTTLE_AUDIT_EXPORT", "5/min"),
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

# Artifact upload limits (configurable via environment)
ARTIFACT_MAX_FILE_SIZE_MB = int(os.getenv("ARTIFACT_MAX_FILE_SIZE_MB", "50"))

# Number of trusted reverse proxies (e.g. nginx, load balancer) sitting in front
# of Django. Used to safely resolve the real client IP from X-Forwarded-For:
# only the rightmost `TRUSTED_PROXY_COUNT` entries are appended by our own infra
# and can be trusted. Set to 0 when Django is exposed directly (no proxy).
TRUSTED_PROXY_COUNT = int(os.getenv("TRUSTED_PROXY_COUNT", "0"))
VIDEO_MAX_FILE_SIZE_MB = int(os.getenv("VIDEO_MAX_FILE_SIZE_MB", "200"))

# Allowed file extensions for artifact uploads, grouped by file type.
ARTIFACT_ALLOWED_EXTENSIONS = {
    # video upload is only available through api/media/videos/
    "image": [".jpg", ".jpeg", ".png"],
    "data": [".csv", ".json"],
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@localhost")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")


CELERY_BROKER_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
MAX_EXPORT_LIMIT = 10000

REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")

if os.getenv("GITHUB_ACTIONS") == "true" or os.getenv("USE_LOCAL_CACHE") == "true":
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "test-cache",
        }
    }
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"
else:
    CACHES = {
        "default": {
            "BACKEND": os.getenv(
                "CACHE_BACKEND", "django.core.cache.backends.redis.RedisCache"
            ),
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "mc",
            "TIMEOUT": 300,
        }
    }

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_CACHE_ALIAS = "default"


SPECTACULAR_SETTINGS = {
    "TITLE": "Mission Control System API",
    "DESCRIPTION": "Documentation for Mission-Control-System",
    "SERVE_INCLUDE_SCHEMA": False,
}


def get_env_or_raise(var_name):
    value = os.getenv(var_name)
    if not value:
        raise ImproperlyConfigured(f"Missing required environment variable: {var_name}")
    return value


STORAGE_PROVIDER = os.getenv("STORAGE_PROVIDER", "local")

FILE_UPLOAD_PERMISSIONS = 0o644

if STORAGE_PROVIDER == "s3":
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_ACCESS_KEY_ID = get_env_or_raise("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = get_env_or_raise("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = get_env_or_raise("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = get_env_or_raise("AWS_S3_REGION_NAME")

    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_FILE_OVERWRITE = False

elif STORAGE_PROVIDER == "minio":
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_ACCESS_KEY_ID = get_env_or_raise("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = get_env_or_raise("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = get_env_or_raise("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = get_env_or_raise("AWS_S3_ENDPOINT_URL")

    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_S3_FILE_OVERWRITE = False

elif STORAGE_PROVIDER == "azure":
    DEFAULT_FILE_STORAGE = "storages.backends.azure_storage.AzureStorage"
    AZURE_ACCOUNT_NAME = get_env_or_raise("AZURE_ACCOUNT_NAME")
    AZURE_ACCOUNT_KEY = get_env_or_raise("AZURE_ACCOUNT_KEY")
    AZURE_CONTAINER_NAME = get_env_or_raise("AZURE_CONTAINER_NAME")

    AZURE_OVERWRITE_FILES = False

elif STORAGE_PROVIDER == "gcs":
    DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
    GS_BUCKET_NAME = get_env_or_raise("GS_BUCKET_NAME")
    GS_CREDENTIALS = get_env_or_raise("GS_CREDENTIALS")

    GS_DEFAULT_ACL = "private"
    GS_QUERYSTRING_AUTH = True
    GS_FILE_OVERWRITE = False

elif STORAGE_PROVIDER == "local":
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

else:
    raise ImproperlyConfigured(f"Unknown STORAGE_PROVIDER: {STORAGE_PROVIDER}")
