# Generated by Django 6.0.5 on 2026-05-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0002_missiondrone_unique_mission_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="missiondrone",
            name="condition_after",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="missiondrone",
            name="condition_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="missiondrone",
            name="flight_ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="missiondrone",
            name="flight_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
