# Generated by Django 6.0.4 on 2026-05-18 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0002_alter_mission_status_missiondrone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="missiondrone",
            name="condition_after",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DAMAGED", "Damaged"),
                    ("LOST", "Lost"),
                    ("MAINTENANCE", "Maintenance"),
                    ("IN_MISSION", "in_mission"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MissionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("target_model", models.CharField(max_length=100)),
                ("target_id", models.IntegerField()),
                ("changes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
