# Generated by Django 6.0.4 on 2026-05-24 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0004_remove_dronestatushistory_related_mission_id_and_more"),
        ("missions", "0003_alter_missiondrone_condition_after_missionauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missiondrone",
            name="condition_after",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DAMAGED", "Damaged"),
                    ("LOST", "Lost"),
                    ("MAINTENANCE", "Maintenance"),
                    ("DECOMMISSIONED", "Decommissioned"),
                    ("SOLD", "Sold"),
                    ("TRANSFERRED", "Transferred"),
                    ("WRITTEN_OFF", "Written off"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="missiondrone",
            name="drone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mission_participations",
                to="drones.drone",
            ),
        ),
    ]
