# Generated by Django 6.0.4 on 2026-05-24 14:19

from django.db import migrations, models

import missions.models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0004_alter_missiondrone_condition_after_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionauditlog",
            name="changes",
            field=models.JSONField(default=missions.models.get_default_changes),
        ),
    ]
