# Generated by Django 6.0.4 on 2026-05-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0004_auditlog_audit_logs_action_781a8f_idx_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="missiondrone",
            name="unique_mission_operator",
        ),
    ]
