# Generated by Django 6.0.4 on 2026-05-28 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import missions.models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0005_remove_missiondrone_unique_mission_operator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("aborted", "Aborted"),
                ],
                default="planned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="missiondrone",
            name="condition_after",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DAMAGED", "Damaged"),
                    ("LOST", "Lost"),
                    ("MAINTENANCE", "Maintenance"),
                    ("DECOMMISSIONED", "Decommissioned"),
                    ("SOLD", "Sold"),
                    ("TRANSFERRED", "Transferred"),
                    ("WRITTEN_OFF", "Written off"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="missiondrone",
            name="mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_drones",
                to="missions.mission",
            ),
        ),
        migrations.AlterField(
            model_name="missiondrone",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operated_mission_drones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MissionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("target_model", models.CharField(max_length=100)),
                ("target_id", models.IntegerField()),
                (
                    "changes",
                    models.JSONField(default=missions.models.get_default_changes),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
