# Generated by Django 6.0.4 on 2026-06-01 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0006_alter_mission_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_action_781a8f_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_logs_created_262184_idx",
        ),
        migrations.AlterModelOptions(
            name="missionauditlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="missionauditlog",
            name="changes",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="missionauditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mission_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="missionauditlog",
            index=models.Index(
                fields=["action", "target_model"], name="mission_aud_action_08f535_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missionauditlog",
            index=models.Index(
                fields=["created_at"], name="mission_aud_created_89ad43_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="missionauditlog",
            table="mission_audit_logs",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
