# Generated by Django 6.0.4 on 2026-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0006_alter_mission_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="incident_notes",
            field=models.TextField(blank=True),
        ),
    ]
