# Generated by Django 6.0.4 on 2026-06-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0007_remove_auditlog_audit_logs_action_781a8f_idx_and_more"),
        ("missions", "0008_alter_missiondrone_condition_after"),
    ]

    operations = []
