# Generated by Django 6.0.4 on 2026-06-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0009_merge_20260603_0806"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="incident_notes",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name="mission",
            name="notes",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
