# Generated by Django 5.2.14 on 2026-06-26 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0016_alter_drone_status_drone_serial_number_gin_idx"),
        ("missions", "0010_alter_mission_incident_notes_alter_mission_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="missiondrone",
            index=models.Index(
                fields=["operator", "mission"], name="operator_mission_idx"
            ),
        ),
    ]
