# Generated by Django 5.2.14 on 2026-07-02 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0020_performance_indexes"),
        ("missions", "0010_alter_mission_incident_notes_alter_mission_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["started_at", "ended_at"], name="mission_time_range_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missiondrone",
            index=models.Index(
                fields=["drone", "mission"], name="md_drone_mission_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missiondrone",
            index=models.Index(
                fields=["operator", "mission"], name="md_operator_mission_idx"
            ),
        ),
    ]
