# Generated by Django 5.2.14 on 2026-07-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0011_missiondrone_operator_mission_idx"),
        ("missions", "0011_performance_indexes"),
    ]

    operations = []
