# Generated by Django 5.2.14 on 2026-07-08 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missions", "0012_merge_20260707_1052"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mission",
            name="missions_status_e455e3_idx",
        ),
        migrations.RemoveIndex(
            model_name="mission",
            name="mission_time_range_idx",
        ),
        migrations.RemoveIndex(
            model_name="missiondrone",
            name="operator_mission_idx",
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["status", "started_at", "ended_at"],
                name="mission_time_range_idx",
            ),
        ),
    ]
