# Generated by Django 5.2.14 on 2026-07-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_usersession_session_key_and_more"),
        ("missions", "0013_remove_mission_missions_status_e455e3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="missions",
                to="accounts.militaryunit",
            ),
        ),
    ]
