# Generated by Django 5.2.14 on 2026-07-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_usersession_session_key_and_more"),
        ("missions", "0015_backfill_mission_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="missions",
                to="accounts.militaryunit",
            ),
        ),
    ]
