# Generated by Django 6.0.5 on 2026-05-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("COMMANDER", "Commander"),
                    ("OPERATOR", "Operator"),
                    ("TECHNICIAN", "Technician"),
                    ("VIEWER", "Viewer"),
                    ("DISPATCHER", "Dispatcher"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
