# Generated by Django 5.0.14 on 2026-05-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('inventory_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('drone_model', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('acquired_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DroneSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_type', models.CharField(max_length=255)),
                ('motor_model', models.CharField(max_length=255)),
                ('battery_type', models.CharField(max_length=255)),
                ('battery_capacity_mah', models.PositiveIntegerField()),
                ('camera_model', models.CharField(max_length=255)),
                ('vtx_model', models.CharField(blank=True, max_length=255)),
                ('flight_controller', models.CharField(max_length=255)),
                ('firmware_version', models.CharField(blank=True, max_length=255)),
                ('max_speed_kmh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_range_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_flight_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('frequency_mhz', models.PositiveIntegerField()),
                ('payload_capacity_g', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='drones.drone')),
            ],
        ),
    ]
