# Generated by Django 6.0.4 on 2026-05-15 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("drones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="military_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drones",
                to="accounts.militaryunit",
            ),
        ),
    ]
