# Generated by Django 6.0.4 on 2026-05-18 11:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0002_drone_military_unit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DAMAGED", "Damaged"),
                    ("LOST", "Lost"),
                    ("MAINTENANCE", "Maintenance"),
                    ("DECOMMISSIONED", "Decommissioned"),
                    ("SOLD", "Sold"),
                    ("TRANSFERRED", "Transferred"),
                    ("WRITTEN_OFF", "Written off"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WriteOffRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("reason_description", models.TextField(blank=True)),
                (
                    "related_mission_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("document_number", models.CharField(blank=True, max_length=100)),
                (
                    "written_off_at",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorized_writeoff_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writeoff_record",
                        to="drones.drone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DroneStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
                (
                    "related_mission_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "related_repair_order_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drone_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_history",
                        to="drones.drone",
                    ),
                ),
                (
                    "related_writeoff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_history_records",
                        to="drones.writeoffrecord",
                    ),
                ),
            ],
        ),
    ]
