# Generated by Django 6.0.4 on 2026-05-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0003_alter_drone_status_writeoffrecord_dronestatushistory"),
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dronestatushistory",
            old_name="related_mission_id",
            new_name="related_mission",
        ),
        migrations.AlterField(
            model_name="dronestatushistory",
            name="related_mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drone_status_history_records",
                to="missions.mission",
            ),
        ),
        migrations.RenameField(
            model_name="writeoffrecord",
            old_name="related_mission_id",
            new_name="related_mission",
        ),
        migrations.AlterField(
            model_name="writeoffrecord",
            name="related_mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="writeoff_records",
                to="missions.mission",
            ),
        ),
    ]
