# Generated by Django 6.0.4 on 2026-05-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0004_remove_dronestatushistory_related_mission_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="classification",
            field=models.CharField(
                choices=[
                    ("CLASS_1", "Class 1"),
                    ("CLASS_2", "Class 2"),
                    ("CLASS_3", "Class 3"),
                ],
                default="CLASS_1",
                max_length=20,
            ),
        ),
    ]
