# Generated by Django 6.0.4 on 2026-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0004_remove_dronestatushistory_related_mission_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="drone_model",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
