# Generated by Django 6.0.4 on 2026-05-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0005_alter_drone_drone_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="drone",
            name="classification",
            field=models.CharField(
                choices=[
                    ("CLASS_1", "Class 1"),
                    ("CLASS_2", "Class 2"),
                    ("CLASS_3", "Class 3"),
                ],
                max_length=20,
                default="CLASS_1",
            ),
        ),
    ]
