# Generated by Django 6.0.4 on 2026-06-01 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0006_drone_classification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dronespec",
            name="additional_modules",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dronespec",
            name="battery_model",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="dronespec",
            name="camera_specs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dronespec",
            name="technical_documentation_url",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="DroneSpecChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_fields", models.JSONField(default=list)),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drone_spec_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drone_spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_history",
                        to="drones.dronespec",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="dronespec_log_created_idx"
                    ),
                    models.Index(
                        fields=["drone_spec", "-created_at"],
                        name="dronespec_log_spec_created_idx",
                    ),
                    models.Index(
                        fields=["changed_by", "-created_at"],
                        name="dronespec_log_user_created_idx",
                    ),
                ],
            },
        ),
    ]
