# Generated by Django 6.0.4 on 2026-05-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "drones",
            "0007_dronespec_additional_modules_dronespec_battery_model_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dronespec",
            name="typical_flight_time_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="dronespec",
            name="typical_range_km",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
