# Generated by Django 6.0.4 on 2026-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "drones",
            "0007_dronespec_additional_modules_dronespec_battery_model_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dronespec",
            name="communication_protocol",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dronespec",
            name="control_channel",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="dronespec",
            name="firmware_file_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="dronespec",
            name="is_firmware_outdated",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the firmware or communication parameters are unsupported.",
            ),
        ),
        migrations.AddField(
            model_name="dronespec",
            name="telemetry_channel",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
