# Generated by Django 6.0.4 on 2026-06-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0008_dronespec_communication_protocol_and_more"),
        ("drones", "0008_dronespec_typical_flight_time_min_and_more"),
    ]

    operations = []
