# Generated by Django 6.0.4 on 2026-06-04 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0009_merge_20260609_1131"),
    ]

    operations = [
        migrations.CreateModel(
            name="DroneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("manufacturer", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "supported_classifications",
                    models.JSONField(
                        default=list, help_text="List of supported classifications"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Drone Model",
                "verbose_name_plural": "Drone Models",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="drone",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RECONNAISSANCE", "Reconnaissance"),
                    ("COMBAT", "Combat"),
                    ("TRANSPORT", "Transport"),
                    ("SURVEILLANCE", "Surveillance"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="drone",
            name="drone_model",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="drone",
            name="drone_model_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="drones.dronemodel",
            ),
        ),
    ]
