# Generated by Django 6.0.4 on 2026-06-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0009_merge_20260609_1137"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dronestatushistory",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="drone",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("IN_MISSION", "In mission"),
                    ("DAMAGED", "Damaged"),
                    ("LOST", "Lost"),
                    ("MAINTENANCE", "Maintenance"),
                    ("DECOMMISSIONED", "Decommissioned"),
                    ("SOLD", "Sold"),
                    ("TRANSFERRED", "Transferred"),
                    ("WRITTEN_OFF", "Written off"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
