# Generated by Django 6.0.4 on 2026-06-04 08:43

from django.db import migrations

from drones.constants import DRONE_MODEL_CLASSIFICATIONS


def migrate_drone_data(apps, schema_editor):
    Drone = apps.get_model("drones", "Drone")
    DroneModel = apps.get_model("drones", "DroneModel")

    for drone in Drone.objects.all():
        drone_model_name = drone.drone_model

        if not drone_model_name:
            continue

        supported = DRONE_MODEL_CLASSIFICATIONS.get(drone_model_name)
        drone_model_obj, _ = DroneModel.objects.get_or_create(
            name=drone_model_name,
            defaults={
                "manufacturer": "Unknown",
                "supported_classifications": supported,
            },
        )

        drone.drone_model_id = drone_model_obj
        drone.classification = supported[0]
        drone.save()


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0010_dronemodel_drone_classification_and_more"),
    ]

    operations = [migrations.RunPython(migrate_drone_data, migrations.RunPython.noop)]
