# Generated by Django 6.0.4 on 2026-06-04 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0011_migrate_drone_models_and_classifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drone",
            name="drone_model",
        ),
        migrations.RenameField(
            model_name="drone",
            old_name="drone_model_id",
            new_name="drone_model",
        ),
        migrations.AlterField(
            model_name="drone",
            name="drone_model",
            field=models.ForeignKey(
                help_text="Drone Model",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drones",
                to="drones.dronemodel",
            ),
        ),
        migrations.AlterField(
            model_name="drone",
            name="classification",
            field=models.CharField(
                choices=[
                    ("RECONNAISSANCE", "Reconnaissance"),
                    ("COMBAT", "Combat"),
                    ("TRANSPORT", "Transport"),
                    ("SURVEILLANCE", "Surveillance"),
                ],
                max_length=20,
            ),
        ),
    ]
