# Generated by Django 5.2.14 on 2026-06-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0010_alter_dronestatushistory_options_alter_drone_status"),
        ("drones", "0012_remove_drone_drone_model_id_and_more"),
    ]

    operations = []
