# Generated by Django 5.2.14 on 2026-06-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0009_merge_20260610_1100"),
        ("drones", "0013_merge_20260611_1520"),
    ]

    operations = []
