# Generated by Django 5.2.14 on 2026-06-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0013_merge_20260611_1520"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writeoffrecord",
            name="reason",
            field=models.CharField(
                choices=[
                    ("LOSS", "Loss"),
                    ("DESTRUCTION", "Destruction"),
                    ("DAMAGE", "Critical damage"),
                    ("OTHER", "Other"),
                ],
                help_text="Canonical reason for writing off the drone.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="writeoffrecord",
            name="reason_description",
            field=models.TextField(
                blank=True,
                help_text="Free-form details about the write-off. Required when the reason is 'Other'.",
            ),
        ),
    ]
