# Generated by Django 6.0.4 on 2026-06-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0009_merge_20260610_1100"),
        ("drones", "0013_merge_20260611_1520"),
    ]

    operations = []
