# Generated by Django 6.0.5 on 2026-06-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0014_alter_writeoffrecord_reason_and_more"),
        ("drones", "0014_merge_20260615_2200"),
    ]

    operations = []
