# Generated by Django 5.2.14 on 2026-06-26 11:20

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userprofile_profile_picture"),
        ("drones", "0015_merge_20260623_1720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drone",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("IN_MISSION", "In mission"),
                    ("DAMAGED", "Damaged"),
                    ("LOST", "Lost"),
                    ("MAINTENANCE", "Maintenance"),
                    ("DECOMMISSIONED", "Decommissioned"),
                    ("SOLD", "Sold"),
                    ("TRANSFERRED", "Transferred"),
                    ("WRITTEN_OFF", "Written off"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=20,
            ),
        ),
        TrigramExtension(),
        migrations.AddIndex(
            model_name="drone",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["serial_number"],
                name="serial_number_gin_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
