# Generated by Django 6.0.4 on 2026-06-21 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0015_merge_20260619_1814"),
        ("missions", "0010_alter_mission_incident_notes_alter_mission_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="writeoffrecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="writeoffrecord",
            index=models.Index(
                fields=["drone", "-created_at"], name="drones_writ_drone_i_93f884_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writeoffrecord",
            index=models.Index(
                fields=["written_off_at"], name="drones_writ_written_67c7cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writeoffrecord",
            index=models.Index(
                fields=["authorized_by", "-created_at"],
                name="drones_writ_authori_26d86e_idx",
            ),
        ),
    ]
