# Generated by Django 6.0.4 on 2026-06-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0014_merge_20260615_2200"),
        ("drones", "0016_dronestatushistory_related_repair_order"),
    ]

    operations = []
