# Generated by Django 5.2.14 on 2026-06-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0015_merge_20260619_1216"),
        ("drones", "0018_merge"),
    ]

    operations = []
