# Generated by Django 5.2.14 on 2026-07-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0016_alter_writeoffrecord_options_and_more"),
        ("drones", "0019_merge_20260630_1009"),
    ]

    operations = []
