# Generated by Django 5.2.14 on 2026-07-02 10:24

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_userprofile_profile_picture"),
        ("drones", "0019_merge_20260630_1009"),
        ("missions", "0010_alter_mission_incident_notes_alter_mission_notes"),
        ("repairs", "0007_merge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="drone",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["serial_number"],
                name="drone_serial_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="drone",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["inventory_number"],
                name="drone_invnum_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="dronestatushistory",
            index=models.Index(
                fields=["drone", "-created_at"], name="dsh_drone_created_idx"
            ),
        ),
    ]
