# Generated by Django 5.2.14 on 2026-07-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0019_merge_0015_merge_20260619_1216_0018_merge"),
        ("drones", "0019_merge_20260630_1009"),
    ]

    operations = []
