# Generated by Django 6.0.5 on 2026-07-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0015_merge_20260623_1040"),
        ("drones", "0020_merge_20260702_1251"),
    ]

    operations = []
