# Generated by Django 5.2.14 on 2026-07-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0020_merge_20260702_1251"),
        ("drones", "0020_performance_indexes"),
    ]

    operations = []
