# Generated by Django 5.2.14 on 2026-07-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0016_alter_drone_status_drone_serial_number_gin_idx"),
        ("drones", "0020_merge_20260702_1251"),
    ]

    operations = []
