# Generated by Django 5.2.14 on 2026-07-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0020_merge_20260701_2157"),
        ("drones", "0020_merge_20260702_1251"),
    ]

    operations = []
