# Generated by Django 5.2.14 on 2026-07-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0021_merge_20260703_1346"),
        ("drones", "0021_merge_20260703_1523"),
    ]

    operations = []
