# Generated by Django 5.2.14 on 2026-07-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0022_merge_20260706_1140"),
        ("drones", "0022_merge_20260706_1705"),
    ]

    operations = []
