# Generated by Django 6.0.5 on 2026-07-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0021_merge_20260706_0827"),
        ("drones", "0022_merge_20260706_1705"),
    ]

    operations = []
