# Generated by Django 5.2.14 on 2026-07-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0023_merge_20260707_1052"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="drone",
            name="serial_number_gin_idx",
        ),
    ]
