# Generated by Django 6.0.5 on 2026-07-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0023_merge_20260708_1019"),
        ("drones", "0024_remove_drone_serial_number_gin_idx"),
    ]

    operations = []
