# Generated by Django 6.0.4 on 2026-06-05 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drones", "0007_dronespec_additional_modules_dronespec_battery_model_and_more"),
        ("missions", "0010_alter_mission_incident_notes_alter_mission_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.FileField(upload_to="artifacts/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("image", "Image"),
                            ("data", "Data"),
                        ],
                        max_length=10,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.PositiveBigIntegerField(help_text="File size in bytes"),
                ),
                ("storage_backend", models.CharField(default="local", max_length=20)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="missions.mission",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_artifacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mission_artifacts",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["mission"], name="mission_art_mission_e31da5_idx"
                    ),
                    models.Index(
                        fields=["uploaded_at"], name="mission_art_uploade_8dc5e6_idx"
                    ),
                    models.Index(
                        fields=["file_type"], name="mission_art_file_ty_4a45e1_idx"
                    ),
                ],
            },
        ),
    ]
