# Generated by Django 6.0.4 on 2026-06-05 14:22

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionartifact",
            name="file",
            field=models.FileField(upload_to=media.models.artifact_upload_path),
        ),
    ]
