# Generated by Django 6.0.4 on 2026-06-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_update_artifact_upload_path"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="missionartifact",
            name="mission_art_mission_e31da5_idx",
        ),
    ]
