# Generated by Django 6.0.4 on 2026-06-10 13:19

import django.core.validators
from django.db import migrations, models

import media.models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_remove_redundant_mission_index_and_uuid_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionartifact",
            name="file",
            field=models.FileField(
                upload_to=media.models.artifact_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp4",
                            "avi",
                            "mov",
                            "jpg",
                            "jpeg",
                            "png",
                            "csv",
                            "json",
                        ]
                    ),
                    media.models._validate_file_size,
                ],
            ),
        ),
    ]
