# Generated by Django 5.2.14 on 2026-06-15 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import media.models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0013_merge_20260611_1520"),
        ("media", "0004_alter_missionartifact_file"),
        ("missions", "0010_alter_mission_incident_notes_alter_mission_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoMetadata",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        max_length=512, upload_to=media.models.video_upload_path
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("content_type", models.CharField(blank=True, max_length=100)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="Optional SHA-256 checksum of the file",
                        max_length=64,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Video recording timestamp from drone metadata",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drone",
                    models.ForeignKey(
                        help_text="Drone used to capture this video",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_metadata",
                        to="drones.drone",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        help_text="Mission associated with this video",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_metadata",
                        to="missions.mission",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded the file",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "video_metadata",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["mission", "drone"],
                        name="video_metad_mission_9da3e8_idx",
                    ),
                    models.Index(
                        fields=["uploader"], name="video_metad_uploade_b56c79_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="video_metad_created_731148_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("file",), name="uq_video_metadata_file"
                    )
                ],
            },
        ),
    ]
