# Generated by Django 5.2.14 on 2026-06-15 22:23

import django.core.validators
from django.db import migrations, models

import media.models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_videometadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionartifact",
            name="file",
            field=models.FileField(
                upload_to=media.models.artifact_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "csv", "json"]
                    ),
                    media.models._validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="videometadata",
            name="file",
            field=models.FileField(
                upload_to=media.models.video_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "avi", "mov", "mkv"]
                    ),
                    media.models.validate_video_file_size,
                ],
            ),
        ),
    ]
