# Generated by Django 5.2.14 on 2026-06-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_mediaauditlog"),
        ("media", "0007_alter_missionartifact_file"),
    ]

    operations = []
