# Generated by Django 5.2.14 on 2026-07-02 10:24

import django.core.validators
from django.db import migrations, models

import media.models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0008_merge_20260630_1009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionartifact",
            name="file",
            field=models.FileField(
                upload_to=media.models.artifact_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "csv", "json"]
                    ),
                    media.models._validate_file_size,
                ],
            ),
        ),
    ]
