# Generated by Django 5.2.14 on 2026-07-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0008_alter_missionartifact_file"),
        ("media", "0008_merge_20260630_1009"),
    ]

    operations = []
