# Generated by Django 5.2.14 on 2026-07-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0009_alter_missionartifact_file"),
        ("media", "0009_merge_20260701_2158"),
    ]

    operations = []
