# Generated by Django 5.2.14 on 2026-07-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0010_merge_20260703_1523"),
        ("media", "0010_merge_20260706_1048"),
    ]

    operations = []
