# Generated by Django 5.2.14 on 2026-07-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0011_merge_20260706_1140"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("download", "Download"),
                    ("upload", "Upload"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("denied", "Permission Denied"),
                ],
                max_length=10,
            ),
        ),
    ]
