# Generated by Django 5.2.14 on 2026-07-29 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drones", "0025_merge_20260716_0138"),
        ("media", "0012_alter_mediaauditlog_action"),
        ("missions", "0013_remove_mission_missions_status_e455e3_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="videometadata",
            name="video_metad_uploade_b56c79_idx",
        ),
        migrations.RenameField(
            model_name="videometadata",
            old_name="uploader",
            new_name="uploaded_by",
        ),
        migrations.AddIndex(
            model_name="videometadata",
            index=models.Index(
                fields=["uploaded_by"], name="video_metad_uploade_9d8ea0_idx"
            ),
        ),
    ]
